### ISSUE TITLE
Unable to run due to circular import issue 

### ISSUE THREAD

**Issue by BhandarkarPawan** [leopiney/neuralnoise#2]
I installed from source and then tried running the cli but ran into this issue

Steps to reproduce: 
1. Create conda env with 3.11.5
2. `pip install .` 
3. `python3 src/neuralnoise/cli.py` 

Ran into: 
```
Traceback (most recent call last):
  File "/Users/pawan/neuralnoise/src/neuralnoise/cli.py", line 1, in <module>
    from pathlib import Path
  File "/Users/pawan/miniconda3/envs/myenv/lib/python3.11/pathlib.py", line 1, in <module>
    import fnmatch
  File "/Users/pawan/miniconda3/envs/myenv/lib/python3.11/fnmatch.py", line 14, in <module>
    import re
  File "/Users/pawan/miniconda3/envs/myenv/lib/python3.11/re/__init__.py", line 124, in <module>
    import enum
  File "/Users/pawan/miniconda3/envs/myenv/lib/python3.11/enum.py", line 3, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/Users/pawan/neuralnoise/src/neuralnoise/types.py", line 1, in <module>
    from textwrap import dedent
  File "/Users/pawan/miniconda3/envs/myenv/lib/python3.11/textwrap.py", line 17, in <module>
    class TextWrapper:
  File "/Users/pawan/miniconda3/envs/myenv/lib/python3.11/textwrap.py", line 76, in TextWrapper
    whitespace = r'[%s]' % re.escape(_whitespace)
                           ^^^^^^^^^
AttributeError: partially initialized module 're' has no attribute 'escape' (most likely due to a circular import)
```

**Comment by leopiney** [comment]
Thanks for reporting this! I made some changes to make it work for the Google Colab version and introduced this bug. This should be fixed in the latest version 1.3.0 now!
